version: 2
jobs:
  build:
    working_directory: ~/cms
    docker:
      - image: circleci/node:4.8.2
      - image: mongo:3.4.4
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm 
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Running Tests
          command: npm test
      - run:
          name: Running Code Coverage
          command: './node_modules/.bin/nyc --reporter=lcov --reporter=text-lcov npm test'
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.json
